server:
  port: 80
spring:
  datasource:
    username: postgres
    password: 1235
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.31.115:5432/memory
  redis:
    database: 0
    host: 192.168.31.115
    port: 6379