### 登录
POST http://{{baseUrl}}/user/login
Content-Type: application/json

{
  "phone": "13540817567",
  "password": "123456"
}

### 获取称呼
GET http://{{baseUrl}}/user/marker
Content-Type: application/json
token:dc4ae97d8fae6e74b4e71b789fc3a60e

###
